# Generated by Django 5.2.17 on 2026-08-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My Store', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=64)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='store_settings_singleton_pk')],
            },
        ),
    ]
