# Generated by Django 5.2.17 on 2026-08-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='reservation_ttl_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
