# Generated by Django 5.2.17 on 2026-08-13 08:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storesettings_reservation_ttl_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='city_fallback_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='delivery_strategy',
            field=models.CharField(choices=[('flat_rate', 'Flat rate'), ('free_above_threshold', 'Free above a threshold'), ('city_based', 'City-based')], default='flat_rate', max_length=32),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='flat_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='free_delivery_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
