# Generated by Django 5.2.17 on 2026-08-13 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storesettings_city_fallback_delivery_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='site_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_message_max_chars',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_template_cancelled',
            field=models.TextField(default='Hi {customer_name}, your order {order_number} has been cancelled. Please contact us if you have any questions.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_template_confirmed',
            field=models.TextField(default="Hi {customer_name}, your order {order_number} has been confirmed! We'll let you know as it progresses."),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_template_delivered',
            field=models.TextField(default='Hi {customer_name}, your order {order_number} has been delivered. Thank you for shopping with us!'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_template_dispatched',
            field=models.TextField(default='Hi {customer_name}, your order {order_number} has been dispatched with {courier_name}. Tracking: {tracking_number}'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_template_out_for_delivery',
            field=models.TextField(default='Hi {customer_name}, your order {order_number} is out for delivery today!'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_template_processing',
            field=models.TextField(default='Hi {customer_name}, your order {order_number} is now being processed.'),
        ),
    ]
