# Generated by Django 5.2.17 on 2026-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storesettings_site_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
