# Generated by Django 5.2.17 on 2026-09-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storesettings_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='show_short_description',
            field=models.BooleanField(default=True),
        ),
    ]
