# Generated by Django 5.2.17 on 2026-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_set_word_similarity_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("checkout", "Checkout"),
                            ("search", "Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("succeeded", models.BooleanField()),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "ip_address", "created_at"],
                        name="core_rateli_scope_c401ae_idx",
                    )
                ],
            },
        ),
    ]
