# Generated by Django 5.2.17 on 2026-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_ratelimitattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratelimitattempt',
            name='scope',
            field=models.CharField(choices=[('login', 'Login'), ('checkout', 'Checkout'), ('search', 'Search'), ('review', 'Review')], max_length=20),
        ),
    ]
