# Generated by Django 5.2.17 on 2026-08-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0002_order_number_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.order'),
        ),
    ]
