# Generated by Django 5.2.17 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockreservation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason',
            field=models.CharField(choices=[('manual', 'Manual adjustment'), ('order_confirmed', 'Order confirmed'), ('order_cancelled', 'Order cancelled after confirmation'), ('order_returned', 'Order returned'), ('order_edited', 'Order edited')], max_length=20),
        ),
    ]
