# Generated by Django 5.2.17 on 2026-08-12 23:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_primary_image_deferred_constraint'),
        # gin_trgm_ops (used below) only exists once pg_trgm is created —
        # Django can't infer this from the index definition itself, since
        # it's an opclass reference, not an FK. Without this dependency,
        # migration order between catalog and core is unconstrained and a
        # fresh `migrate` can apply this before the extension exists.
        ('core', '0001_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('search_text', config='simple'), name='product_search_tsv_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='product_search_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
