# Generated by Django 5.2.17 on 2026-08-12 23:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_search_tsv_gin',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_search_trgm_gin',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('search_text', config='simple'), fastupdate=False, name='product_search_tsv_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=False, fields=['search_text'], name='product_search_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
