# Generated by Django 5.2.17 on 2026-08-14 10:10

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_productslugredirect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                upload_to="brands/",
                validators=[core.validators.validate_image_upload_size],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="categories/",
                validators=[core.validators.validate_image_upload_size],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/originals/",
                validators=[core.validators.validate_image_upload_size],
            ),
        ),
    ]
