# Generated by Django 5.2.17 on 2026-08-13 08:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['city'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('city'), name='deliveryzone_city_unique_ci')],
            },
        ),
    ]
