# Generated by Django 5.2.17 on 2026-08-13 08:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_search_indexes_fastupdate_off'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_whatsapp_number', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_instructions', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_to_dispatch', 'Ready to Dispatch'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned'), ('expired', 'Expired')], default='pending_confirmation', max_length=32)),
                ('payment_method', models.CharField(default='whatsapp_pending', max_length=32)),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], max_length=32, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_status', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('merchant_notes', models.TextField(blank=True, default='')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('courier_name', models.CharField(blank=True, default='', max_length=100)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
