# Generated by Django 5.2.17 on 2026-08-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordereditevent_orderstatusevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTrackingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('order_number', models.CharField(blank=True, default='', max_length=20)),
                ('succeeded', models.BooleanField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='orders_orde_ip_addr_290e64_idx')],
            },
        ),
    ]
