# Generated by Django 5.2.17 on 2026-09-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_base_notes_product_heart_notes_and_more'),
        ('orders', '0004_ordertrackingattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.TextField(max_length=2000)),
                ('is_approved', models.BooleanField(default=False)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='product_review_rating_1_to_5')],
            },
        ),
    ]
